DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  public_key VARCHAR(255) DEFAULT NULL,
  secret_key VARCHAR(255) DEFAULT NULL,
  host BOOLEAN DEFAULT FALSE,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  city VARCHAR(255) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  bio VARCHAR(300) DEFAULT NULL,
  day_rate INT DEFAULT 15,
  social_link VARCHAR(255) DEFAULT NULL,
  thumbs_up INT DEFAULT 1,
  thumbs_down INT DEFAULT 1,
  connect_id VARCHAR(255) DEFAULT NULL,
  customer_id VARCHAR(255) DEFAULT NULL,
  uid VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  verified BOOLEAN DEFAULT FALSE
);
