DROP TABLE IF EXISTS bookings CASCADE;

CREATE TABLE bookings (
  id SERIAL PRIMARY KEY NOT NULL,
  host_key VARCHAR(255) DEFAULT NULL,
  user_key VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  title VARCHAR(255) DEFAULT NULL,
  color VARCHAR(255) DEFAULT NULL,
  start_time VARCHAR(255) DEFAULT NULL,
  end_time VARCHAR(255) DEFAULT NULL,
  stamp DATE DEFAULT NOW()
);
